### ISSUE TITLE
unable to authenticate with keyboard-interactive method

### ISSUE THREAD

**Issue by sans-c** [DDoSolitary/yasfw#1]
Your screenshot shows that interactive authentication via passwords should be possible. However when I try to connect to a remote server, yasfw gives me

> >yasfw.exe --mount-point A --server x.x.x.x --removable --dokan-debug --user user
Mar 15 18:39:07.504 INFO initializing, dokan_driver_version: 400, dokan_version: 131
Mar 15 18:39:07.739 INFO connected established, server_public_key: xxxx
Mar 15 18:39:07.889 ERRO authentication failed, server_auth_methods: PUBLICKEY | INTERACTIVE, auth_result: Denied

without any option to ever enter a password. I didn't try they key file option yet.

Edit: Okay, so you only check for "password" and not "interactive" as possible ssh authentication modes. Seems like in my specific case "interactive" works just like "password". Might be worth adding. :)

**Comment by DDoSolitary** [comment]
Unfortunately keyboard-interactive authentication hasn't been supported yet

**Comment by DDoSolitary** [comment]
Keyboard interactive authentication is now supported by the latest [dev snapshots](https://dl.bintray.com/ddosolitary/dev-releases/yasfw/). Let me know if you encounter any problems.

**Comment by sans-c** [comment]
Appears to work, thanks!
