### ISSUE TITLE
volume label after mounting

### ISSUE THREAD

**Issue by the-Arioch** [DDoSolitary/yasfw#30]
when mounted the volume label is set like `root@193.169.173.82:22`

which was okay until `-C` option (mount target AKA local chroot) was introduced

now it is well feasible that several different folders be mounted on the same server.

perhaps it would be nice if `yafsw` would change default label then (but - potentially a filename length limit? dunno).

maybe it would be nice if yafsw would provide an option to override default volume label

also, if i change volume label from Explorer it seems to work and propagate across applications. 
So, maybe (if we assume yasfw to be called by design from script files) it is of lesser use, we could run `label` command in a "parallel thread" to yasw, except that yasfw does not warrant to actually use the provided, fixed drive letter (#29), D'oh...

Also, BTW, what happens with the changed volume label? is it somehow propagated to SSH server and change somethign there? i wonder. Probably not, probably it is RAM-only thing, but being not documented anywhere leaves me with a bit of F.U.D.

**Comment by DDoSolitary** [comment]
I'm not sure what's happening under the hood for renaming. My code always returns the "user@host:ip" string. Probably there's some magic in Dokan or Windows.

Anyways, it sounds good to add an option to customize the label.

**Comment by the-Arioch** [comment]
But at least you are certain yasfw does not have code to implement volume renaming and push it down NFS link.
That is nice to know.
