### ISSUE TITLE
wish: read-only mount flag

### ISSUE THREAD

**Issue by the-Arioch** [DDoSolitary/yasfw#31]
just to feel safe working with legacy systems, can there be an option makign double sure yafsw would fail any write operations and only read operations would be allowed?

if Dokan's `mirror` can be see some example (to keep consistent) then it has
` /w (write-protect drive)                       Read only filesystem.`

**Comment by DDoSolitary** [comment]
Sounds good. Will do.

**Comment by the-Arioch** [comment]
`short("R")` - is it a good idea?

it might be occasionally be mistaken with 'removable drive' "-r" and it is distinct from `mirror`'s /w for apparently no reason.

**Comment by DDoSolitary** [comment]
mirror chooses the `w` from the flag name (write protect), but personally I don't like that and prefer "read only".

Short names are meant to be used by those who are familiar with the program and understand what they mean, so I think it's OK to use `R`.

**Comment by the-Arioch** [comment]
>  but personally I don't like that and prefer "read only".

Me too (in general) but in this specific case personally i would prefer "upstream" consistency. Though it is highly subjective indead.
